version: '3'

services:
  node1:
    container_name: cm-node1
    hostname: cm-node1
    image: "chainmakerofficial/chainmaker:v1.2.3"
    restart: always
    working_dir: "/chainmaker-go/bin"
    command: "./chainmaker start -c ../config/wx-org1.chainmaker.org/chainmaker.yml"
    ports:
      - "11301:11301"
      - "12301:12301"
    volumes:
      - ../build/config/node1:/chainmaker-go/config/wx-org1.chainmaker.org
      - node1_data:/chainmaker-go/data
    networks:
      localnet:
        aliases:      
          - cm-node1
        ipv4_address: 172.44.1.11
  node2:
    container_name: cm-node2
    hostname: cm-node2
    image: "chainmakerofficial/chainmaker:v1.2.3"
    restart: always
    working_dir: "/chainmaker-go/bin"
    command: "./chainmaker start -c ../config/wx-org2.chainmaker.org/chainmaker.yml"
    ports:
      - "11302:11302"
      - "12302:12302"
    volumes:
      - ../build/config/node2:/chainmaker-go/config/wx-org2.chainmaker.org
      - node2_data:/chainmaker-go/data
    networks:
      localnet:
        aliases:      
          - cm-node2
        ipv4_address: 172.44.1.12
  node3:
    container_name: cm-node3
    hostname: cm-node3
    image: "chainmakerofficial/chainmaker:v1.2.3"
    restart: always
    working_dir: "/chainmaker-go/bin"
    command: "./chainmaker start -c ../config/wx-org3.chainmaker.org/chainmaker.yml"
    ports:
      - "11303:11303"
      - "12303:12303"
    volumes:
      - ../build/config/node3:/chainmaker-go/config/wx-org3.chainmaker.org
      - node3_data:/chainmaker-go/data
    networks:
      localnet:
        aliases:      
          - cm-node3
        ipv4_address: 172.44.1.13
  node4:
    container_name: cm-node4
    hostname: cm-node4
    image: "chainmakerofficial/chainmaker:v1.2.3"
    restart: always
    working_dir: "/chainmaker-go/bin"
    command: "./chainmaker start -c ../config/wx-org4.chainmaker.org/chainmaker.yml"
    ports:
      - "11304:11304"
      - "12304:12304"
    volumes:
      - ../build/config/node4:/chainmaker-go/config/wx-org4.chainmaker.org
      - node4_data:/chainmaker-go/data
    networks:
      localnet:
        aliases:      
          - cm-node4
        ipv4_address: 172.44.1.14

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.1.0/16

volumes:
  node1_data: {}  
  node2_data: {}  
  node3_data: {}  
  node4_data: {}  
